sudo: true

language: python

python:
  - 2.7

env:
  global:
    - MCDIR=/tmp/mcdir
    - MCDB_TYPE=rethinkdb
    - MCDB_NAME=materialscommons
    - MCDB_FILE=test_setup/rethinkdb_dump_test_data.tar.gz
    - MCDB_PORT=30815
    - MCDB_CONNECTION=localhost:$MCDB_PORT
    - RETHINKDB_CLUSTER_PORT=31815
    - RETHINKDB_HTTP_PORT=8090

install:
  - git clone https://github.com/materials-commons/materialscommons.org.git
  - pushd materialscommons.org/backend
  - sh mcservers start -u
  - popd
  - cd python
  - pip install -r requirements.txt
  - python setup.py install --user

before_script:
  - rethinkdb --driver-port $MCDB_PORT --cluster-port $RETHINKDB_CLUSTER_PORT --http-port $RETHINKDB_HTTP_PORT --daemon
  - sleep 5
  - rethinkdb restore $MCDB_FILE --connect $MCDB_CONNECTION --force

script:
  - pytest

